package com.zeepoint.model;
// Generated Jun 29, 2015 2:10:42 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Contact generated by hbm2java
 */
@Entity
@Table(name="contact"
    ,catalog="zipoints"
)
public class Contact  implements java.io.Serializable {


     private long id;
     private Zipuser zipuserByUser;
     private Zipuser zipuserByContactId;

    public Contact() {
    }

    public Contact(long id, Zipuser zipuserByUser, Zipuser zipuserByContactId) {
       this.id = id;
       this.zipuserByUser = zipuserByUser;
       this.zipuserByContactId = zipuserByContactId;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user", nullable=false)
    public Zipuser getZipuserByUser() {
        return this.zipuserByUser;
    }
    
    public void setZipuserByUser(Zipuser zipuserByUser) {
        this.zipuserByUser = zipuserByUser;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="contactId", nullable=false)
    public Zipuser getZipuserByContactId() {
        return this.zipuserByContactId;
    }
    
    public void setZipuserByContactId(Zipuser zipuserByContactId) {
        this.zipuserByContactId = zipuserByContactId;
    }




}


