package com.zeepoint.model;
// Generated Jun 29, 2015 2:10:42 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name="message"
    ,catalog="zipoints"
)
public class Message  implements java.io.Serializable {


     private Long id;
     private Zeepoint zeepoint;
     private Zipuser zipuser;
     private String message;
     private Date date;
     private int delivered;
     private int messageType;

    public Message() {
    }

    public Message(Zeepoint zeepoint, Zipuser zipuser, String message, Date date, int delivered, int messageType) {
       this.zeepoint = zeepoint;
       this.zipuser = zipuser;
       this.message = message;
       this.date = date;
       this.delivered = delivered;
       this.messageType = messageType;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="zeepoint", nullable=false)
    public Zeepoint getZeepoint() {
        return this.zeepoint;
    }
    
    public void setZeepoint(Zeepoint zeepoint) {
        this.zeepoint = zeepoint;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user", nullable=false)
    public Zipuser getZipuser() {
        return this.zipuser;
    }
    
    public void setZipuser(Zipuser zipuser) {
        this.zipuser = zipuser;
    }

    
    @Column(name="message", nullable=false, length=144)
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", nullable=false, length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="delivered", nullable=false)
    public int getDelivered() {
        return this.delivered;
    }
    
    public void setDelivered(int delivered) {
        this.delivered = delivered;
    }

    
    @Column(name="message_type", nullable=false)
    public int getMessageType() {
        return this.messageType;
    }
    
    public void setMessageType(int messageType) {
        this.messageType = messageType;
    }




}


