package com.zeepoint.model;
// Generated May 21, 2015 1:31:25 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Message generated by hbm2java
 */
@Entity
@Table(name="message"
//    ,catalog="zipoints"
)
public class Message  implements java.io.Serializable {


     private Long id;
     private User user;
     private Zeepoint zeepoint;
     private String message;
     private Date date;

    public Message() {
    }

    public Message(User user, Zeepoint zeepoint, String message, Date date) {
       this.user = user;
       this.zeepoint = zeepoint;
       this.message = message;
       this.date = date;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="zeepoint", nullable=false)
    public Zeepoint getZeepoint() {
        return this.zeepoint;
    }
    
    public void setZeepoint(Zeepoint zeepoint) {
        this.zeepoint = zeepoint;
    }

    
    @Column(name="message", nullable=false, length=45)
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", nullable=false, length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


