package com.zeepoint.model;
// Generated Jun 29, 2015 2:10:42 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pmessage generated by hbm2java
 */
@Entity
@Table(name="pmessage"
    ,catalog="zipoints"
)
public class Pmessage  implements java.io.Serializable {


     private Long id;
     private Zipuser zipuserByFromUserId;
     private Zipuser zipuserByToUserId;
     private String message;
     private Date date;
     private int received;
     private int messageType;

    public Pmessage() {
    }

    public Pmessage(Zipuser zipuserByFromUserId, Zipuser zipuserByToUserId, String message, Date date, int received, int messageType) {
       this.zipuserByFromUserId = zipuserByFromUserId;
       this.zipuserByToUserId = zipuserByToUserId;
       this.message = message;
       this.date = date;
       this.received = received;
       this.messageType = messageType;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fromUserId", nullable=false)
    public Zipuser getZipuserByFromUserId() {
        return this.zipuserByFromUserId;
    }
    
    public void setZipuserByFromUserId(Zipuser zipuserByFromUserId) {
        this.zipuserByFromUserId = zipuserByFromUserId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="toUserId", nullable=false)
    public Zipuser getZipuserByToUserId() {
        return this.zipuserByToUserId;
    }
    
    public void setZipuserByToUserId(Zipuser zipuserByToUserId) {
        this.zipuserByToUserId = zipuserByToUserId;
    }

    
    @Column(name="message", nullable=false, length=100)
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", nullable=false, length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="received", nullable=false)
    public int getReceived() {
        return this.received;
    }
    
    public void setReceived(int received) {
        this.received = received;
    }

    @Column(name="message_type", nullable=false)
    public int getMessageType() {
        return this.messageType;
    }
    
    public void setMessageType(int messageType) {
        this.messageType = messageType;
    }


}


