package com.zeepoint.model;
// Generated Jun 7, 2015 6:25:26 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pmessage generated by hbm2java
 */
@Entity
@Table(name="pmessage"
    ,catalog="zipoints"
)
public class Pmessage  implements java.io.Serializable {


     private Long id;
     private Zipuser zipuserByUser1;
     private Zipuser zipuserByUser2;
     private String message;
     private Date date;
     private int received1;
     private int received2;

    public Pmessage() {
    }

    public Pmessage(Zipuser zipuserByUser1, Zipuser zipuserByUser2, String message, Date date, int received1, int received2) {
       this.zipuserByUser1 = zipuserByUser1;
       this.zipuserByUser2 = zipuserByUser2;
       this.message = message;
       this.date = date;
       this.received1 = received1;
       this.received2 = received2;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user1", nullable=false)
    public Zipuser getZipuserByUser1() {
        return this.zipuserByUser1;
    }
    
    public void setZipuserByUser1(Zipuser zipuserByUser1) {
        this.zipuserByUser1 = zipuserByUser1;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user2", nullable=false)
    public Zipuser getZipuserByUser2() {
        return this.zipuserByUser2;
    }
    
    public void setZipuserByUser2(Zipuser zipuserByUser2) {
        this.zipuserByUser2 = zipuserByUser2;
    }

    
    @Column(name="message", nullable=false, length=100)
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", nullable=false, length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="received1", nullable=false)
    public int getReceived1() {
        return this.received1;
    }
    
    public void setReceived1(int received1) {
        this.received1 = received1;
    }

    
    @Column(name="received2", nullable=false)
    public int getReceived2() {
        return this.received2;
    }
    
    public void setReceived2(int received2) {
        this.received2 = received2;
    }




}


