package com.zeepoint.model;
// Generated May 21, 2015 1:31:25 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Room generated by hbm2java
 */
@Entity
@Table(name="room"
//    ,catalog="zipoints"
    , uniqueConstraints = @UniqueConstraint(columnNames="userid") 
)
public class Room  implements java.io.Serializable {


     private Long id;
     private User user;
     private Zeepoint zeepoint;
     private Integer status;

    public Room() {
    }

    public Room(User user, Zeepoint zeepoint, Integer status) {
       this.user = user;
       this.zeepoint = zeepoint;
       this.status=status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="userid", unique=true, nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="zeepointId", nullable=false)
    public Zeepoint getZeepoint() {
        return this.zeepoint;
    }
    
    public void setZeepoint(Zeepoint zeepoint) {
        this.zeepoint = zeepoint;
    }

    /**
     * @return the status
     */
     @Column(name="status", nullable=false)
    public Integer getStatus() {
        return status;
    }

    /**
     * @param status the status to set
     */
    public void setStatus(Integer status) {
        this.status = status;
    }




}


