package com.zeepoint.model;
// Generated May 21, 2015 1:31:25 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
//    ,catalog="zipoints"
    , uniqueConstraints = @UniqueConstraint(columnNames="fb_id") 
)
public class User  implements java.io.Serializable {


     private Long id;
     private Long fbId;
     private String name;
     private Integer age;
     private String email;
     private String gender;
     private String imageurl;
     private String deviceId;
     private Set<Room> rooms = new HashSet<Room>(0);
     private Set<Message> messages = new HashSet<Message>(0);
     private Set<UserRoles> userRoleses = new HashSet<UserRoles>(0);
     private Set<Zeepoint> zeepoints = new HashSet<Zeepoint>(0);

    public User() {
    }

    public User(Long fbId, String name, Integer age, String email, String gender, String imageurl, String deviceId, Set<Room> rooms, Set<Message> messages, Set<UserRoles> userRoleses, Set<Zeepoint> zeepoints) {
       this.fbId = fbId;
       this.name = name;
       this.age = age;
       this.email = email;
       this.gender = gender;
       this.imageurl = imageurl;
       this.deviceId = deviceId;
       this.rooms = rooms;
       this.messages = messages;
       this.userRoleses = userRoleses;
       this.zeepoints = zeepoints;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    
    @Column(name="fb_id", unique=true)
    public Long getFbId() {
        return this.fbId;
    }
    
    public void setFbId(Long fbId) {
        this.fbId = fbId;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="age")
    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }

    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="gender", length=20)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    
    @Column(name="imageurl", length=80)
    public String getImageurl() {
        return this.imageurl;
    }
    
    public void setImageurl(String imageurl) {
        this.imageurl = imageurl;
    }

    
    @Column(name="device_id", length=45)
    public String getDeviceId() {
        return this.deviceId;
    }
    
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Room> getRooms() {
        return this.rooms;
    }
    
    public void setRooms(Set<Room> rooms) {
        this.rooms = rooms;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Message> getMessages() {
        return this.messages;
    }
    
    public void setMessages(Set<Message> messages) {
        this.messages = messages;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<UserRoles> getUserRoleses() {
        return this.userRoleses;
    }
    
    public void setUserRoleses(Set<UserRoles> userRoleses) {
        this.userRoleses = userRoleses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="user")
    public Set<Zeepoint> getZeepoints() {
        return this.zeepoints;
    }
    
    public void setZeepoints(Set<Zeepoint> zeepoints) {
        this.zeepoints = zeepoints;
    }




}


