package com.zeepoint.model;
// Generated Jun 29, 2015 2:10:42 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Zeepoint generated by hbm2java
 */
@Entity
@Table(name="zeepoint"
    ,catalog="zipoints"
    , uniqueConstraints = @UniqueConstraint(columnNames="reference_id") 
)
public class Zeepoint  implements java.io.Serializable {


     private Long id;
     private City city;
     private Country country;
     private State state;
     private Zipuser zipuser;
     private String name;
     private String referenceId;
     private BigDecimal longitud;
     private BigDecimal latitud;
     private Integer distance;
     private String description;
     private Set<Message> messages = new HashSet<Message>(0);
     private Set<Room> rooms = new HashSet<Room>(0);

    public Zeepoint() {
    }

	
    public Zeepoint(Zipuser zipuser, String name, String referenceId, BigDecimal longitud, BigDecimal latitud) {
        this.zipuser = zipuser;
        this.name = name;
        this.referenceId = referenceId;
        this.longitud = longitud;
        this.latitud = latitud;
    }
    public Zeepoint(City city, Country country, State state, Zipuser zipuser, String name, String referenceId, BigDecimal longitud, BigDecimal latitud, Integer distance, String description, Set<Message> messages, Set<Room> rooms) {
       this.city = city;
       this.country = country;
       this.state = state;
       this.zipuser = zipuser;
       this.name = name;
       this.referenceId = referenceId;
       this.longitud = longitud;
       this.latitud = latitud;
       this.distance = distance;
       this.description = description;
       this.messages = messages;
       this.rooms = rooms;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="city_id")
    public City getCity() {
        return this.city;
    }
    
    public void setCity(City city) {
        this.city = city;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="country_id")
    public Country getCountry() {
        return this.country;
    }
    
    public void setCountry(Country country) {
        this.country = country;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="state_id")
    public State getState() {
        return this.state;
    }
    
    public void setState(State state) {
        this.state = state;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="creator", nullable=false)
    public Zipuser getZipuser() {
        return this.zipuser;
    }
    
    public void setZipuser(Zipuser zipuser) {
        this.zipuser = zipuser;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="reference_id", unique=true, nullable=false, length=45)
    public String getReferenceId() {
        return this.referenceId;
    }
    
    public void setReferenceId(String referenceId) {
        this.referenceId = referenceId;
    }

    
    @Column(name="longitud", nullable=false, precision=11, scale=8)
    public BigDecimal getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(BigDecimal longitud) {
        this.longitud = longitud;
    }

    
    @Column(name="latitud", nullable=false, precision=10, scale=8)
    public BigDecimal getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(BigDecimal latitud) {
        this.latitud = latitud;
    }

    
    @Column(name="distance")
    public Integer getDistance() {
        return this.distance;
    }
    
    public void setDistance(Integer distance) {
        this.distance = distance;
    }

    
    @Column(name="description", length=45)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="zeepoint")
    public Set<Message> getMessages() {
        return this.messages;
    }
    
    public void setMessages(Set<Message> messages) {
        this.messages = messages;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="zeepoint")
    public Set<Room> getRooms() {
        return this.rooms;
    }
    
    public void setRooms(Set<Room> rooms) {
        this.rooms = rooms;
    }




}


