package com.zeepoint.communication;
// Generated Apr 12, 2015 2:37:02 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Zeepoint generated by hbm2java
 */

public class ZeepointOUT extends BaseOUT {


     private long id;
     private String name;
     private String referenceId;
     private String ownerId;
     private BigDecimal longitud;
     private BigDecimal latitud;
     private Integer distance;
     private Integer users;
     private Integer listeners;
     private boolean joined=false;
     private String description;

    public ZeepointOUT() {
    }

	
//    public ZeepointOUT(long id, String name, String referenceId, BigDecimal longitud, BigDecimal latitud, Integer distance) {
//        this.id = id;
//        this.name = name;
//        this.referenceId = referenceId;
//        this.longitud = longitud;
//        this.latitud = latitud;
//    }

    
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getReferenceId() {
        return this.referenceId;
    }
    
    public void setReferenceId(String referenceId) {
        this.referenceId = referenceId;
    }

    public BigDecimal getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(BigDecimal longitud) {
        this.longitud = longitud;
    }

    public BigDecimal getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(BigDecimal latitud) {
        this.latitud = latitud;
    }
    
    public Integer getDistance() {
        return this.distance;
    }
    
    public void setDistance(Integer distance) {
        this.distance = distance;
    }
    
    public Integer getUsers() {
        return this.users;
    }
    
    public void setUsers(Integer users) {
        this.users = users;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + (new Long(id).intValue());
        //result = prime * result + ((referenceId == null) ? 0 : referenceId.hashCode());
        return result;
    }
 
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (!(obj instanceof ZeepointOUT))
            return false;
        ZeepointOUT other = (ZeepointOUT) obj;
        if (id!=0 && other.id!=0 && id == other.id){
            return true;
        }
        if (referenceId != null) {
            if (other.referenceId != null)
                if (referenceId.equals(other.referenceId))
                    return true;
        }
        return false;
    }

    /**
     * @return the joined
     */
    public boolean isJoined() {
        return joined;
    }

    /**
     * @param joined the joined to set
     */
    public void setJoined(boolean joined) {
        this.joined = joined;
    }

    /**
     * @return the description
     */
    public String getDescription() {
        return description;
    }

    /**
     * @param description the description to set
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * @return the listeners
     */
    public Integer getListeners() {
        return listeners;
    }

    /**
     * @param listeners the listeners to set
     */
    public void setListeners(Integer listeners) {
        this.listeners = listeners;
    }

    /**
     * @return the ownerId
     */
    public String getOwnerId() {
        return ownerId;
    }

    /**
     * @param ownerId the ownerId to set
     */
    public void setOwnerId(String ownerId) {
        this.ownerId = ownerId;
    }


}


